version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html # Mount your project directory for development
    ports:
      - "8000:80" # Map host port 8000 to container port 80
    environment:
      # Configure your Laravel .env variables here, or ensure they are present in your .env file
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: laravel
    volumes:
      - db_data:/var/lib/mysql # Persist database data

volumes:
  db_data:
